// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJV6XjUxAO0ffWZARDRA_9rEwxFBh5eVY',
    appId: '1:168833930954:web:65a1ac7d4f850640954633',
    messagingSenderId: '168833930954',
    projectId: 'fir-live-score-e3879',
    authDomain: 'fir-live-score-e3879.firebaseapp.com',
    storageBucket: 'fir-live-score-e3879.firebasestorage.app',
    measurementId: 'G-P2QJ4SH22C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJTwPg6QsncpeXfTn5TYYAYWCgAJfPUMI',
    appId: '1:168833930954:android:0dd7b4f948115076954633',
    messagingSenderId: '168833930954',
    projectId: 'fir-live-score-e3879',
    storageBucket: 'fir-live-score-e3879.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLR-3z4aopJYxZrLM-VXvEX7l7u3XkoQs',
    appId: '1:168833930954:ios:b524f6cd2b946a9a954633',
    messagingSenderId: '168833930954',
    projectId: 'fir-live-score-e3879',
    storageBucket: 'fir-live-score-e3879.firebasestorage.app',
    iosBundleId: 'com.example.firebaseLiveScore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLR-3z4aopJYxZrLM-VXvEX7l7u3XkoQs',
    appId: '1:168833930954:ios:b524f6cd2b946a9a954633',
    messagingSenderId: '168833930954',
    projectId: 'fir-live-score-e3879',
    storageBucket: 'fir-live-score-e3879.firebasestorage.app',
    iosBundleId: 'com.example.firebaseLiveScore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJV6XjUxAO0ffWZARDRA_9rEwxFBh5eVY',
    appId: '1:168833930954:web:b1714ec8aca2cef1954633',
    messagingSenderId: '168833930954',
    projectId: 'fir-live-score-e3879',
    authDomain: 'fir-live-score-e3879.firebaseapp.com',
    storageBucket: 'fir-live-score-e3879.firebasestorage.app',
    measurementId: 'G-QRMFM5TDR6',
  );

}